"""split_run_stats

Revision ID: 3e6023f4dfac
Revises: 
Create Date: 2026-03-11 04:28:50.650099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6023f4dfac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('records_processed', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('records_created', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('records_updated', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_column('records_ingested')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('records_ingested', sa.INTEGER(), nullable=False, server_default='0'))
        batch_op.drop_column('records_updated')
        batch_op.drop_column('records_created')
        batch_op.drop_column('records_processed')

    # ### end Alembic commands ###
